disabled_rules:
  - file_length
  - force_cast
  - force_try
  - identifier_name
  - line_length
  - todo
  - trailing_comma
  - type_body_length
  - vertical_whitespace

opt_in_rules:
  - closure_end_indentation         # Closure end should have the same indentation as the line that started it.
  - closure_spacing                 # Closure expressions should have a single space inside each brace.
  - explicit_init                   # Explicitly calling .init() should be avoided.
  - overridden_super_call           # Some Overridden methods should always call super.

excluded:
  - Carthage
  - Pods
  - .build
  - vendor

# Rule Configuration
closure_spacing:
  severity: error
colon:
  severity: error
comma:
  severity: error
cyclomatic_complexity:
  ignores_case_statements: true
explicit_init:
  severity: error
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
opening_brace:
  severity: error
overridden_super_call:
  severity: error
redundant_optional_initialization:
  severity: error
return_arrow_whitespace:
  severity: error
statement_position:
  severity: error
trailing_newline:
  severity: error
trailing_semicolon:
  severity: error
trailing_whitespace:
  severity: error
private_over_fileprivate:
  severity: warning
type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 100

custom_rules:
  extra_header_comments:
    name: "File header comments"
    regex: '(^\/\/ *$)|(^\/\/ *[A-Za-z]+\.swift$)|(^\/\/ *Created by \w*)'
    match_kinds:
      - comment
    message: "Clean up file header comments."
