fastlane_version "1.82.0"
default_platform :ios

desc "Tests, increases the version number and tags. By default it will increase the patch, use type:minor or type:major to increase the respective option"
lane :release do |options|
    project = "OwlBanners.xcodeproj"
    type = options[:type] || 'patch'

    ensure_git_status_clean
    ensure_git_branch
    increment_version_number(
        xcodeproj: project
    )
    increment_build_number(
        xcodeproj: project
    )
    commit_version_bump(
        message: 'Version Bump',
        xcodeproj: project
    )

    new_version = get_version_number(xcodeproj: project)
    tag_name = "v#{new_version}"
    add_git_tag(tag: tag_name)
    push_to_git_remote
end
